services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: eshop
    ports:
     - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d eshop"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - "pgdata:/var/lib/postgresql"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  eshop:
    image: eshop
    build: .
    ports:
      - 8081:8000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "eshopdata:/app/media"

volumes:
  pgdata:
  eshopdata: